[build]
  command = "wget -q -O stork https://files.stork-search.net/releases/v1.6.0/stork-ubuntu-20-04 && chmod +x stork && export PATH=$PATH:$(pwd) && make publish"
  publish = "output"

[build.environment]
  PYTHON_VERSION = "3.13"
